# Generated by Django 4.1.5 on 2023-01-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler_text', '0002_fillertextmodel_original_alter_fillertextmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillertextmodel',
            name='original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
