# Generated by Django 4.1.5 on 2023-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler_text', '0003_alter_fillertextmodel_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillertextmodel',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fillertextmodel',
            name='value',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
