# Generated by Django 4.1.5 on 2023-01-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filler_text', '0004_rename_title_fillertextmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillertextmodel',
            options={'verbose_name_plural': 'ダミーテキスト'},
        ),
    ]
